update examples to remove deprecated methods
RIAEvangelist/node-cmd pull request #52
Opened 2021-06-01 02:49 UTC by BarrBrian

Simply swapped out the to-be-deprecated "get" methods from 3 of the code examples and replaced them with "run."

From a scan of the code it looks like getSync was already deprecated.

2021-07-05 07:26 UTC, RIAEvangelist commented
`get` is not going to be depricated for sure, let me check the code for the others. I was just using get today. Super handy.

2021-07-05 07:27 UTC, RIAEvangelist commented
OK then, I stand corrected. Can you also remove get from the cmd.js file. Lets finish up the deprication.

Thank you!

2021-07-05 07:28 UTC, RIAEvangelist requested changes
please also remove get from the `cmd.js`

2021-07-14 01:59 UTC, BarrBrian commented
@RIAEvangelist - PR updated :)

Definitely think the semantics of `run` is more clear. Happy to help. This was super handy in a recent project.

2021-07-29 00:22 UTC, RIAEvangelist requested changes
I am going to make this an official rev before I merge as it is a breaking change

2021-07-29 00:23 UTC, merged

2021-07-29 00:23 UTC, RIAEvangelist commented
I decided I would just rev it before publishing.